- name: ec2 launcher
  hosts: localhost
  connection: local
  become: False
  tasks:
  - name: launching ec2
    ec2:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      key_name: "{{ key_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      region: "{{ region }}"
      wait: yes
      group: default
      count: 1
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      wait: yes
      assign_public_ip: yes
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_dns_name }}"
    wait_for_connection:
      delay: 60
      timeout: 320
    loop: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  tasks:
  - name: Transfer docker install script
    copy: src=prepare_env.sh dest=~ mode=0777

  - name: Execute the script to install docker
    command: sh ~/prepare_env.sh

  - name: Transfer install master script
    copy: src=install_master.sh dest=~ mode=0777
    when: master_node is defined

  - name: Transfer database configuration
    copy: src=database.sql dest=~ mode=0777
    when: master_node is defined

  - name: Transfer nextcloud config
    copy: src=nextcloud.conf dest=~ mode=0777
    when: master_node is defined

  - name: Execute the install master script
    command: sh ~/install_master.sh
    when: master_node is defined